### PR TITLE
Fix remove symbols when removing more than one symbol. Close #6.

### LINKED ISSUE #6: IndexOutOfBoundsException
How to reproduce: type some input, bacskpace, type - backspace and so on. After couple of iterations there is a crash

> FATAL EXCEPTION: main
>                                                                         Process: com.thrd.maskededitbox, PID: 11763
>                                                                         java.lang.IndexOutOfBoundsException: replace (15 ... 16) ends beyond length 15
>                                                                             at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1090)
>                                                                             at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:498)
>                                                                             at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:492)
>                                                                             at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:491)
>                                                                             at com.github.pinball83.maskededittext.MaskedEditText$MaskedInputFilter.filter(MaskedEditText.java:327)
>                                                                             at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:502)
>                                                                             at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:492)
>                                                                             at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:491)
>                                                                             at android.text.method.NumberKeyListener.onKeyDown(NumberKeyListener.java:121)
>                                                                             at android.widget.TextView.doKeyDown(TextView.java:6095)
>                                                                             at android.widget.TextView.onKeyDown(TextView.java:5908)
>                                                                             at android.view.KeyEvent.dispatch(KeyEvent.java:2640)
>                                                                             at android.view.View.dispatchKeyEvent(View.java:9240)
>                                                                             at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
>                                                                             at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
>                                                                             at android.widget.ScrollView.dispatchKeyEvent(ScrollView.java:379)
>                                                                             at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
>                                                                             at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
>                                                                             at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
>                                                                             at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
>                                                                             at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
>                                                                             at com.android.internal.policy.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:2395)
>                                                                             at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1727)
>                                                                             at android.app.Activity.dispatchKeyEvent(Activity.java:2731)
>                                                                             at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:50)
>                                                                             at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:224)
>                                                                             at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2310)
>                                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4127)
>                                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4089)
>                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
>                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
>                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
>                                                                             at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
>                                                                             at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
>                                                                             at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
>                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
>                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
>                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
>                                                                             at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
>                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
>                                                                             at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
>                                                                             at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
>                                                                             at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
>                                                                             at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3434)
>                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                             at android.os.Looper.loop(Looper.java:148)
>                                                                             at android.app.ActivityThread.main(ActivityThread.java:5417)
>                                                                             at java.lang.reflect.Method.invoke(Native Method)
>                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

### PR DESCRIPTION
**Pull request by Nublo**
Fix remove symbols when removing more than one symbol. Close #6.

### CODE REVIEW

**Comment by ejohansson** [comment]
Any updates on when this will get merged?

**Comment by jlubeck** [comment]
Will this ever get merged?

**Comment by Tieru** [comment]
It doesn't really fix the issue on some keyboards

//UPD: Sorry, works fine

**Comment by dimmduh** [comment]
Merge please. U can install fixed version from @Nublo repo via gradle
`compile 'com.github.Nublo:masked-edittext:eeb70445d313647870a9fc398d997a6a65e1d673'`

**Comment by kenshin6x** [comment]
Please Merge !

**Pull request merged**
